### ISSUE TITLE
specs: parcours embarquement v0

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#920]
From [Notion](https://www.notion.so/betagouv-dinum/Embarquement-beta-1ba59e111b8b8000b51ad2723f092163)

### Home

<img width="708" alt="Image" src="https://github.com/user-attachments/assets/d65f05c8-3e93-4e1a-a09c-2b2a9fbb0969" />

### Onglet dans la fiche membre

<img width="715" alt="Image" src="https://github.com/user-attachments/assets/f952d89d-1724-4ddf-84b1-4b4dd7f48952" />

## Règles

 - N'importe quel utilisateur peut cocher/décocher les cases de n'importe quel autre (v0)
 - Les cases à cocher sont présentes directement dans un onglet de la fiche membre
 - Cette feature ne sera visible dans un 1er temps que sur les fiches des membres arrivés apres le 1/1/2025
 - On historise qui a coché quoi quand pour qui

## Données

Actuellement on a plusieurs groupe de règles qui seront communs à tout le monde.

Dans le futur des règles additionnelles pourront être proposées:
 - en fonction du domaine de l'utilisateur
 - en fonction de son incubateur

Idéalement le règles sont éditables par toute l'équipe

ex:

```yaml
- title: Découvrir l'écosystème de beta.gouv.fr
  items:
  - id: fiche-membre
    title: Créer ma fiche membre
  - id: atelier-onboarding
    title: |
      Assister à [un atelier d'embarquement](https://doc.incubateur.net/communaute/travailler-chez-beta.gouv.fr/to-do-darrivee/embarquement-dans-la-communaute)
  - id: forum-beta
    title: Assister à [un forum Beta.gouv.fr](https://doc.incubateur.net/communaute/decouvrir-beta.gouv.fr/la-communaute/les-rituels/seminaire)
  - id: valeurs-beta
    title: 
      Découvrir [les valeurs de beta.gouv.fr](https://doc.incubateur.net/communaute/decouvrir-beta.gouv.fr/valeurs)
  - id: video-fondamentaux-culture-administrative
    title: |
      Regarder la vidéo [Fondamentaux de la culture administrative](https://tube.numerique.gouv.fr/w/wgpehK9PTp5npJQ3Bp9K27)
  - id: rapport-etonnement
    title: Rédiger mon Rapport d'étonnement
- title: Comprendre les standards de beta.gouv.fr
  items:
  - id: standards-beta
    title: |
      Découvrir [les standards de qualité de beta.gouv.fr](https://doc.incubateur.net/communaute/gerer-son-produit/les-standards)
  - id: formation-hygiene-secu
    title: Assister à la formation Hygiène de sécurité
  - id: atelier-verifier-accesibilite
    title: Assister à l'atelier Vérifier l'accessibilité de mon service
```

Pour un profil tech par on pourrait avoir en plus (v2) :

```yaml
- title: Le métier de tech chez beta
  items:
  - id: onboarding-dev
    title: |
      Assister à l'onboarding dev
  - id: atelier-securiser-mon-poste-de-dev
    title: Assister à l'atelier Sécuriser mon poste de dev
```
